common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: zonodon
  password:

development:
  <<: *common
  database: glittery_development

test: &test
  <<: *common
  database: glittery_test

production:
  <<: *common
  database: glittery_production

cucumber:
  <<: *test
